---
title: "Homework 5"
author: "Na Yun Cho"
output: pdf_document
---
```{r}
library(tidyverse)
library(mlbench)
library(ISLR)
library(caret)
library(e1071)
library(kernlab)
library(DALEX)
```

```{r, message = FALSE}
data(OJ)
# partition the data into training set and test set 
oj = OJ %>% mutate(Store7 = recode(Store7, '1' = 'Yes', '0' = 'No'), Store7 = as.numeric(Store7))
set.seed(1)
rowTrain <- createDataPartition(y = oj$Purchase, p =799/1070, list = FALSE)

train_df = oj[rowTrain,]
test_df = oj[-rowTrain,]

dim(train_df) #has 800 observations
dim(test_df) #has 270 observations
```

## (a)
```{r}
ctrl <- trainControl(method = "cv")

set.seed(1)
svml.fit <- train(Purchase  ~ ., 
                  data = train_df, 
                  method = "svmLinear2",
                  preProcess = c("center", "scale"),
                  tuneGrid = data.frame(cost = exp(seq(-3,-1,len = 40))),
                  trControl = ctrl)

plot(svml.fit, highlight = TRUE)

#training error rate 
mean(predict(svml.fit) != train_df$Purchase)
#test error rate
mean(predict(svml.fit, newdata = test_df) != test_df$Purchase)
```


```{r}
svmr.grid <- expand.grid(C = exp(seq(-4,0,len=10)),
                         sigma = exp(seq(-5,-3,len=20)))
set.seed(1)             
svmr.fit <- train(Purchase~., 
                  data = train_df,
                  method = "svmRadial",
                  preProcess = c("center", "scale"),
                  tuneGrid = svmr.grid,
                  trControl = ctrl)

plot(svmr.fit, highlight = TRUE)

#training error rate
mean(predict(svmr.fit) != train_df$Purchase)
#test error rate 
mean(predict(svmr.fit, newdata = test_df) != test_df$Purchase)
```





